name: Tasks
main: fun.sunrisemc.tasks.TasksPlugin
version: ${project.version}
api-version: 1.18
author: TheFishNextDoor
description: A simple task plugin
softdepend: [Vault]
commands:
  tasks:
    description: List your current tasks
    usage: /tasks
  level:
    description: Check your level and experience
    usage: /level
    aliases: [skips, upcomingunlocks]
  unlocks:
    description: List your unlocks
    usage: /unlocks
  tasksadmin:
    description: Admin commands for tasks plugin
    usage: /tasksadmin
    permission: tasks.admin
    aliases: [ta]
permissions:
  tasks.color:
    description: Allows the player to change the color of their tasks
    default: true
  tasks.admin:
    description: Allows the player to use admin commands
  tasks.admin.reload:
    description: Allows the player to reload the plugin
  tasks.admin.task:
    description: Allows the player to alter players tasks
  tasks.admin.xp:
    description: Allows the player to alter players xp
  tasks.admin.unlock:
    description: Allows the player to alter players unlocks
  tasks.admin.skips:
    description: Allows the player to alter players skips