package com.thefishnextdoor.tasks.task;

public enum TriggerType {
    INTERACT_ENTITY,
    DAMAGE_ENTITY,
    KILL_ENTITY,
    BUCKET_ENTITY,
    SHEAR_ENTITY,
    MANIPULATE_ARMORSTAND,
    ENCHANT_ITEM,
    CONSUME_ITEM,
    HARVEST_ITEM,
    BREAK_ITEM,
    SHEAR_ITEM,
    BREAK_BLOCK,
    PLACE_BLOCK,
    HARVEST_BLOCK,
    TAKE_LECTERN_BOOK,
    DEATH,
    TIMER;
}